new/urls.py
from django.urls import path
from . import views
app_name = 'new'

urlpatterns=[
    # path('',views.index,name='index'),
    # path('<int:question_id>/',views.detail,name='detail'),
    # path('<int:question_id>/results/',views.results,name='results'),
    # path('<int:question_id>/vote',views.vote,name='vote'),
    path('',views.IndexView.as_view(),name='index'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

newprjt/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('new/',include('new.urls')),
    path('testapp/',include('testapp.urls'))
]

testapp/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index')
]

new/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

testapp/models.py
from django.db import models

# Create your models here.

new/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question
from django.http import Http404
from django.template import loader
from django.shortcuts import get_object_or_404,render
from django.urls import reverse
from .models import Choice ,Question
from django.views import generic
from django.utils import timezone




# Create your views here.
# def index(request):
#     # # return HttpResponse("HELLO, I AM NEETHU ANTONY")
#     # latest_question_list=Question.objects.order_by('-pub_date')[:5]
#     # # output=','.join([q.question_text for q in latest_question_list])
#     # template=loader.get_template('new/index.html')
#     # # return HttpResponse(output)
#     # context={
#     #     'latest_question_list':latest_question_list,
#     # }
#     # return HttpResponse(template.render(context,request))
#
#         latest_question_list = Question.objects.order_by('-pub_date')[:5]
#         context = {'latest_question_list': latest_question_list}
#         return render(request, 'new/index.html', context)
#
# def detail(request,question_id):
#     # # return HttpResponse("you are looking at question %s." %question_id)
#     # try:
#     #     question = Question.objects.get(pk=question_id)
#     # except Question.DoesNotExist:
#     #     raise Http404("Question does not exist")
#     # return render(request, 'new/detail.html', {'question': question})
#     question=get_object_or_404(Question,pk=question_id)
#     return render(request,'new/detail.html',{'question':question})
#
# def results(request,question_id):
#     # response="you are looking at the result of question %s."
#     # return HttpResponse(response % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'new/results.html', {'question': question})

def vote(request,question_id):
    # return HttpResponse("you are voting on question %s."% question_id)
    question=get_object_or_404(Question,pk=question_id)
    try:
        selected_choice=question.choice_set.get(pk=request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,'new/detail.html',{
            'question':question,
            'error_message':"you dint select a choice.",
        })
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('new:results',args=(question.id,)))


class IndexView(generic.ListView):
    template_name ='new/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        # return Question.objects.order_by('-pub_date')[:5]
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'new/detail.html'
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'new/results.html'

testapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return HttpResponse("test in test app")

new/templates/new/detail.html
<h1>{{ question.question_text}}</h1>
<ul>
    {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }}</li>
    {% endfor %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'new:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
         <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
         <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
<input type="submit" value="vote">
</form>
</ul>

new/templates/new/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'new/style.css' %}">
{%  if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
{#            <li><a href="/new/{{ question.id }}/">{{ question.question_text }}</a></li>#}
{#              <li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>#}
                <li><a href="{% url 'new:detail' question.id %}">{{ question.question_text }}</a></li>

    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

new/templates/new/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'new:detail' question.id %}">Vote again?</a>